### PR TITLE
fix(types): Change type to lowercase boolean

### LINKED ISSUE #33: [2.0.3] `LogMessage` interface using `Boolean` vs `boolean`
Noticed this then when casting my own copy of the `LogMessage` and `HooksOption` type until exported.

https://github.com/logdna/logdna-browser/blob/v2.0.3/src/logdna.d.ts#L65

When using [**@typescript-eslint/ban-types**](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-types.md) linting rule, the linter autofixes `Boolean` to `boolean`.

Because `Boolean !== boolean`, it causes:

```
TS2322: Type 'LogHooksOption' is not assignable to type 'HooksOption'.   
Types of property 'beforeSend' are incompatible. 
...        
Types of property 'disableStacktrace' are incompatible.               
Type 'Boolean | undefined' is not assignable to type 'boolean | undefined'.                 
Type 'Boolean' is not assignable to type 'boolean | undefined'.
```

Normally I would assume this is developer preference, but I note that all the historic types are cast as primitives eg https://github.com/logdna/logdna-browser/blob/v2.0.3/src/logdna.d.ts#L37 so I imagine this inconsistency was possibly due to linting not running in CI etc?

### PR DESCRIPTION
**Pull request by TerryMooreII**
Summary:
Change from Boolean to boolean type
fixes #33 

Semver: patch

### CODE REVIEW

File: src/logdna.d.ts [hunk 1]
```diff
@@ -62,7 +62,7 @@ export type LogMessage = {
   message: any;
   lineContext?: Object;
   errorContext?: Object;
```
Comment (prescience-data) [inline src/logdna.d.ts:64]: These could / should also be the primitive `object` as well.

**Review by joemaddalone — APPROVED** [review]
