### PR TITLE
fix(unhandledPromise): `error.message` is overwritten

### LINKED ISSUE #38: Losing the original error message
Usually, the javascript error object already have the `message` property, so this code is overriding the original message that is being lost:

https://github.com/logdna/logdna-browser/blob/7f7d7274ba15792e7451e14ca0a31a1bc84a9f8f/src/plugins/global-handler.ts#L26-L48

image

### PR DESCRIPTION
**Pull request by TerryMooreII**
Summary:
Fix bug where unhandledPromiseRejection handler was overwritting
the `error.message` with <unknown>
Fix #38

Semver: patch

### CODE REVIEW

**Review by joemaddalone — APPROVED** [review]

File: src/plugins/global-handler.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ const addUnhandledrejection = () => {
 
 /*  istanbul ignore next */
 const onUnhandledRejection = (e: any) => {
-  let error = e;
+  let error: any = {};
```
Comment (lmcarreiro) [inline src/plugins/global-handler.ts:28]: Now sure, but now if one of `e.reason` or `e.detail.reason` is a string, even if `e instanceof Error`, it will lose the stack trace info, because  `else if (typeof reason === 'string')` comes before `else if (e instanceof Error)`.
